### ISSUE TITLE
Feature Request - Safe Whitelabel for not yet tested versions

### ISSUE THREAD

**Issue by TornMarketing** [nickian/mautic-whitelabeler#103]
Hey mate

How does the white labelling specifically work? 
ie it checking specific files? or a known string within a directory of files.

Thinking a quick bandaid solution between version updates would be offer a lite whitelabel that replaces the hex codes and the logo graphics.
 
These are not likely to change long term in the code and would be rather safe to run a generic PHP script find/replace all within xyz directory.

**Comment by nickian** [comment]
A quick explanation of how it works:

There are several files within Mautic that have branding baked into them. I basically make a copy of all of these files (what you see in the `templates` folder) and replace the branding with template tags (e.g., {{company_name}}). Then, I use PHP `str_replace` to go through and find these template tags and replace them with the input you provide. Each release may have slightly different files, so I just create a new template folder for each release (sometimes I can just copy the last one when there are no changes).

When there's a new release, I download the files into a folder next to the previous release and run `compare.php` after updating the folder names in this file.

```php
$v1_path = '../3.2.5';
$v2_path = '../3.3.1';
```

When running `php compare.php` in the command line, it gives you this. These are the files that are modified. Except 1.core.js is no longer used for anything in newer versions of Mautic, so we can ignore that for now:

```
<pre>Array
(
    [/app/bundles/CoreBundle/Views/Default/base.html.php] => Same
    [/app/bundles/CoreBundle/Views/Default/head.html.php] => Same
    [/app/bundles/CoreBundle/Views/LeftPanel/index.html.php] => Same
    [/app/bundles/UserBundle/Views/Security/base.html.php] => Same
    [/app/bundles/CoreBundle/Assets/css/app.css] => Same
    [/app/bundles/CoreBundle/Assets/css/libraries/libraries.css] => Same
    [/app/bundles/CoreBundle/Assets/js/1.core.js] => Different
    [/app/bundles/CoreBundle/Assets/js/1a.content.js] => Same
)
```

But for example's sake, we can see that there were some changes to `1.core.js`. 

<img width="1614" alt="Screen Shot 2021-03-04 at 11 25 11 AM" src="https://user-images.githubusercontent.com/590678/110011158-58d5fb80-7cdc-11eb-876a-1b492c61d437.png">

You can see how the files have changed by comparing the releases: https://github.com/mautic/mautic/compare/3.2.5...3.3.1

This file is actually no longer relevant since around < Mautic 2.15.0. The company name info was moved to `1a.content.js`. In this case, I simply copy the template folder from the last release and renamed it, and everything works fine. However, sometimes these files do change and you must update the template files first. If you just ignored these changes and ran the whitelabeler, you'd be replacing Mautic's new code with code from the last release and you'd probably break your installation. 

All of the functions are in the `whitelabel.php` file if you want to see exactly how everything is done.

I'm not sure what a band-aid version would look like or if that is a good idea. I wouldn't be so eager to update your Mautic install so quickly on production installs anyway. There have been so many times they prematurely release a new version and it's simply not ready and things are broken. I recommend having a testing environment that you thoroughly test before updating your production environment, or it least give it a week or more for any potential bugs to be worked out in a release.
