### ISSUE TITLE
Compatibility with Mautic 3.3.4

### ISSUE THREAD

**Issue by ilsebrase** [nickian/mautic-whitelabeler#116]
Hi, im very new to Mautic.  Got version 3.3.4 installed on a server wanting to use the whitelabeler plugin but noticed its not compatible with the current version.  With being new in Mautic, what would you suggest is the easiest way to get labeler to work?

**Comment by nickian** [comment]
Please read the README.md document. It says support is currently for up to 3.3.3. However, I'm releasing support for 3.3.4 in the next day or two. In the mean time, you should be able to simply copy the folder in templates called "3.3.3" and rename it "3.3.4" and this should work without any issues, since there weren't any changes to the files between those two versions.
