### ISSUE TITLE
Mautic 4.3.1 error

### ISSUE THREAD

**Issue by zietbukuel** [nickian/mautic-whitelabeler#140]
I'm trying to apply my own styles in a Mautic 4.3.1 install, but it fails with the following message:

```
Whitelabeling...
Updating colors...
CSS files updated with new colors!
Updating company name in templates...
Updated company name in templates!
Updating logo files...
Logos updated!
Clearing Mautic cache...
PHP Warning:  require_once(/home/forge/mautic.mysite.com/public/app/autoload.php): failed to open stream: No such file or directory in /home/forge/mautic.mysite.com/public/mautic-whitelabeler/whitelabeler.php on line 567

Warning: require_once(/home/forge/mautic.mysite.com/public/app/autoload.php): failed to open stream: No such file or directory in /home/forge/mautic.mysite.com/public/mautic-whitelabeler/whitelabeler.php on line 567
PHP Fatal error:  require_once(): Failed opening required '/home/forge/mautic.mysite.com/public/app/autoload.php' (include_path='.:/usr/share/php') in /home/forge/mautic.mysite.com/public/mautic-whitelabeler/whitelabeler.php on line 567

Fatal error: require_once(): Failed opening required '/home/forge/mautic.mysite.com/public/app/autoload.php' (include_path='.:/usr/share/php') in /home/forge/mautic.mysite.com/public/mautic-whitelabeler/whitelabeler.php on line 567
```

I have the file in the right place, I own all the files under my username, but for some reason it cannot read it.

**Comment by zietbukuel** [comment]
I also want to mention that the permissions are right and that I can see the file and also open it. Not sure why the whitelabeler isn't able to.

**Comment by TonyBogdanov** [comment]
Hi @zietbukuel, Mautic has changed the location of `autoload.php` since 4.3.0, I think, that's why it can't find the file.
This was fixed 29 days ago, but hasn't been released yet, see here: https://github.com/nickian/mautic-whitelabeler/commit/c34e6236a34cad1f39ac6b4688dae48f508ca9cc

I think the author is waiting to add 4.4 support in the next release, but it might take some time due to the added support for PHP 8, or at least that's how I see it.

For the time being you can use the `master` branch rather than 2.2.5.

**Comment by nickian** [comment]
This should be resolved now.
