### ISSUE TITLE
Composer Issue not finding Mautic URL

### ISSUE THREAD

**Issue by ShareBtech** [nickian/mautic-whitelabeler#141]
Hi,

As we get closer to Mautic 5 I decided to go ahead and update a test instance to composer.  I went and tried to run the whitelabeller and am getting Mautic not found: HTTP/2 500. (from cmd: .nvalid URL provided, Mautic not found: HTTP/2 500)
I have tried both from command line and UI.

With composer they have now moved everything to docroot, so i have updated the json file to reflect the new change. I am running 4.4.2 which it is seeing as compatible.

So i see in line 58 of whitelabeler.php it is looking for the file LICENSE.txt and I see that composer is not adding this file to docroot.  After I copied this file to docroot from another instance I ran the command line and all worked.

Just an FYI if anyone is having the same issue

**Comment by nickian** [comment]
I'm not sure I understand the point of the composer install. I always download a package or use the built-in updater. But I went ahead and changed the validation to look for `favicon.ico` instead of `LICENSE.txt`, since that appears to consistently be in the root directory. Hopefully that solves the issue.

**Comment by nickian** [comment]
I have found that with the new 5+ versions you have to make sure to do `composer install` even if you download a release zip file in order for the whitelabeler to work. It must install some development dependencies that allow you to generate assets and clear the cache.
