### ISSUE TITLE
Footers company name should not be edited

### ISSUE THREAD

**Issue by namalesamamira** [nickian/mautic-whitelabeler#16]
> Copyright 2017 Mautic. All Rights Reserved. 

I am no lawyer but I think this footer should not be editable. Wouldn't it be misleading to say that you own the rights to Mautic?

**Comment by nickian** [comment]
I'm no lawyer either, but Mautic is licensed under GPL (https://en.wikipedia.org/wiki/GNU_General_Public_License), so that means you can modify it however you wish and redistribute or sell it under the same license. In other words, as long as it remains open source.

I can create an optional footer change in the next update, so that the footer modification is separate from the company name that appears in the title tag. That way if someone wants to leave the Mautic copyright, they have the option.
