### ISSUE TITLE
Url not found (solved)

### ISSUE THREAD

**Issue by isaipanelinha** [nickian/mautic-whitelabeler#25]
How to solve url problem not found (solved)

1 - Download the latest version of whitelabeler, here in Github;
2 - Upload to the Mautic root directory; (Eg mymautic/whitelabeler/)
3 - Open file version.txt and modify to 2.12.1. (mymautic/app/version.txt/)
4 - Access the whitelabeler url and make the label modifications.
5. After making the label modifications with whitelabeler, return the "version.txt" file to the current version (2.13.1 or higher)

**Comment by imrodmartin** [comment]
hmmm
I'm getting constant redirects with the final error "To many redirects"... 
permissions/ownership is correct... 
any thoughts?

**Comment by nickian** [comment]
Shouldn't have to do this now since I updated it. But you may be able to do this on future versions if I'm slow to update (I'll try not to be).  However, it's just a coincidence that it worked on 2.13.1 because there were not changes to the core files that the whitelabeler modifies since the last version. Sometimes there are changes, so you could potentially break something.

This is what the `compare.php` files is for in the root directory of the whitelabeler. 

```
<?php

// Compare a new release of Mautic to see if the files whitelabeling affects have been modified.

require_once('whitelabeler.php');
$whitelabeler = new Whitelabeler;

$v1_path = '/path/to/mautic-2.13.1';
$v2_path = '/path/to/mautic-2.12.2 2';

$compare = $whitelabeler->compareMauticVersions($v1_path, $v2_path);

echo '<pre>';
print_r($compare);
echo '</pre>';
```

So you have to download the last supported version of Mautic and the newest version from the releases page of their GitHub. Then unzip the files and update the $v1 and $v2 paths in the code above. Then run compare.php. It will give you something like this:

```
Array
(
    [/app/bundles/CoreBundle/Views/Default/base.html.php] => Same
    [/app/bundles/CoreBundle/Views/Default/head.html.php] => Same
    [/app/bundles/CoreBundle/Views/LeftPanel/index.html.php] => Same
    [/app/bundles/UserBundle/Views/Security/base.html.php] => Same
    [/app/bundles/CoreBundle/Assets/css/app.css] => Same
    [/app/bundles/CoreBundle/Assets/css/libraries/libraries.css] => Same
    [/app/bundles/CoreBundle/Assets/js/1.core.js] => Same
    [/app/bundles/CoreBundle/Assets/js/1a.content.js] => Same
)
```

If they all say "same" then no changes have been made by the Mautic developers to these files. So you can just copy the last supported version's folder in /templates and name it to the new version. However, if they don't all say "same" and something says "different," then those files need to be updated in the template folder to the new version of the file (these files have template tags in them and end up replacing files in your Mautic installation).
