### ISSUE TITLE
cli: specify config file on command line.

### ISSUE THREAD

**Issue by virgilwashere** [nickian/mautic-whitelabeler#53]
Possibly like this:

```bash
php ./cli.php --whitelabel --config=./assets/bluetheme.json

```

Thanks for what you've added to v2 so far Nick!

**Comment by nickian** [comment]
Good idea. I added this to the latest release. Now you can just use:

`php cli.php --whitelabel your-file.json`

It looks for the file in the assets folder. Maybe your idea of specifying the full path is better. I can add that option as well. Maybe if the second argument starts with `--conifg=` it will use the full path, otherwise if a filename is given it will just look in assets.

**Comment by virgilwashere** [comment]
Thinking out loud...

Update `.gitignore` to support local `.json` config files without causing a dirty tree.


```gitignore
!**/assets/config.json
**/assets/*.json
```

Possibly also ignore:

- [x] `sidebar_logo`
- [x] `favicon`
- [x] `login_logo`

On my phone, checking code to see if filenames for above are consistent or based on uploaded files and my sample names are coincidentally matching...

**Comment by nickian** [comment]
This is also updated in 2.0.2. Now you can do three things from the command line:

`php cli.php --whitelabel` - Looks for config.json

`php cli.php --whitelabel other_file.json` - Looks for other_file.json in assets folder.

`php cli.php --whitelabel --config=/path/other_file.json` - Looks for JSON file anywhere else you want.

Assets and backups are ignored by git now as well.
