### ISSUE TITLE
Issues on server running Mautic behind self-signed SSL

### ISSUE THREAD

**Issue by TonyBogdanov** [nickian/mautic-whitelabeler#62]
Seems like the whitelabeler (the frontend) is having difficulties when Mautic is using SSL and the certificate is either self-signed or invalid.

There are primarily two issues here, the uploaded images will always report as "not being there" even though they are indeed in the assets folder. That's because the code checking if they exist `assetExists` uses cURL, which fails to verify the connection.

Secondly, you'll always get an error about the Mautic URL being invalid because of the same reason (can't verify host), although in this particular case the error comes from this line instead: `$license = substr(file_get_contents($url.'/LICENSE.txt' ...`.

I'm not 100% sure but I think it's not just the frontend experiencing this problem, but I also think you'd be unable to whitelabel even from CLI.

This is easily fixable and I'll be sending a pull request shortly, but there's a philosophical question to be considered. Should the whitelabeler allow Mautic to be run behind and invalid certificate?

My personal opinion is - YES, I don't see one single valid reason why the tool should concern itself with how Mautic is setup or if it's secure or not.

**Comment by nickian** [comment]
I agree. Thanks.

**Comment by luxuryrealtygroup** [comment]
.powered_wsdesk span
                        {
                            opacity: 0.4;
                            font-size: 10px;
                            color: black;
                        }
                        .powered_wsdesk a
                        {
                            opacity: 0.4;
                            font-size: 10px;
                            color: black !important;
                        }
                    
                    
                     Your request (#427) has been received on September 26, 2019 10:43 pm and is being reviewed by our support staff.                                To add additional comments, reply to this email.                                                                Your Issue:                                Seems like the whitelabeler (the frontend) is having difficulties when Mautic is using SSL and the certificate is either self-signed or invalid.

There are primarily two issues here, the uploaded images will always report as "not being there" even though they are indeed in the assets folder. That's because the code checking if they exist `assetExists` uses cURL, which fails to verify the connection.

Secondly, you'll always get an error about the Mautic URL being invalid because of the same reason (can't verify host), although in this particular case the error comes from this line instead: `$license = substr(file_get_contents($url.'/LICENSE.txt' ...`.

I'm not 100% sure but I think it's not just the frontend experiencing this problem, but I also think you'd be unable to whitelabel even from CLI.

This is easily fixable and I'll be sending a pull request shortly, but there's a philosophical question to be considered. Should the whitelabeler allow Mautic to be run behind and invalid certificate?

My personal opinion is - YES, I don't see one single valid reason why the tool should concern itself with how Mautic is setup or if it's secure or not.

-- 
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/nickian/mautic-whitelabeler/issues/62
                                Tags : No Tags                                Regards,                                Support 
                Email is a service from Talega Systems. Powered by WSDesk
