### ISSUE TITLE
Logo image's URL should be relative

### ISSUE THREAD

**Issue by amz-x** [nickian/mautic-whitelabeler#68]
I think the image URL paths should be relative. Regardless if the Mautic installation has a domain name / A-record prefix or not, the whitelabeler needs to re-run if moving the installation to a new environment. Removing the $url prefix in the replaceImages function should do the trick.

I willing to create a PR if you agree with the above statement?

**Comment by nickian** [comment]
We have to use absolute URLs because of how Mautic handles URLs. 

For example, on the login page URL: `http://mautic-domain.com/s/login`

We can't use `src="media/images/login_logo.png"` because Mautic adds the `s` in the URL, so it ends up pointing to src="http://mautic-domain.com/s/media/images/login_logo.png"`

And we can't use `src="/media/images/login_logo.png"` because some users run Mautic in a subdirectory and this points to the root.

So we have to stick with `$url.'/media/images/login_logo.png'`

**Comment by amz-x** [comment]
@nickian - I understand. Would you mind if I look for a way to hook into Mautic's way of adding the prefix / url and apply that as the substitute?

**Comment by nickian** [comment]
@amz-x Sure. I'm not sure how or why Mautic does that. But feel free to update this thread if you find a way to make it a relative link that will work for everyone.

**Comment by zanchin** [comment]
@nickian For users who run Mautic in a subdirectory, a relative `$url` config value such as `/mautic` would still work, while keeping the `config.json` generic enough to move between multiple installs.

So instead of removing `$url` altogether, is it possible to relax the validation restrictions to just a URL-like path, and not try to make a CURL call to it? Or only try the CURL validation if it's a full URL (for backwards compatibility).

I'm happy to submit a PR if you agree with the direction.

This would be a necessary change for anyone who wants to build the custom theme into a docker image that can be deployed to different environments with their own domains without needing additional configuration.

**Comment by FerRubioMorales** [comment]
Maybe another way to do this id using base html tag, getting the absolute url to be dynamic.

Example:

‘’’
<base href="https://www.w3schools.com/" target="_blank">
</head>

<body>
<img src="images/stickman.gif" width="24" height="39" alt="Stickman">
‘’’

**Comment by amz-x** [comment]
@nickian - I've submitted a PR for review. 

By using ``` src="<?php echo $view['assets']->getUrl('{{image}}') ?>" ``` in the templates & passing in relative URL's for replacement, it covers the case scenarios where Mautic is in a subdirectory or root directory.
